### ISSUE TITLE
A problem when pressing the like or dislike buttons

### ISSUE THREAD

**Issue by yoniker** [buurzx/tinderCloneUI#2]
I'm getting this exception when trying to press the buttons. This might be an issue with Flutter itself.

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while rebuilding dirty elements:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4268 pos 12: '!_dirty': is not
true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was:
  CardStack file:///C:/Users/Yoni/Projects/tinderCloneUI/lib/main.dart:123:17

When the exception was thrown, this was the stack:
#2      Element.rebuild (package:flutter/src/widgets/framework.dart:4268:12)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
#4      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
#5      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#8      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
#12     _invoke (dart:ui/hooks.dart:253:10)
#13     _drawFrame (dart:ui/hooks.dart:211:3)
(elided 5 frames from class _AssertionError and dart:async)

The element being rebuilt at the time was index 0 of 2:
  CardStack
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while rebuilding dirty elements:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4268 pos 12: '!_dirty': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  CardStack file:///C:/Users/Yoni/Projects/tinderCloneUI/lib/main.dart:123:17
When the exception was thrown, this was the stack: 
#2      Element.rebuild (package:flutter/src/widgets/framework.dart:4268:12)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
#4      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
#5      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
...
The element being rebuilt at the time was index 0 of 2: CardStack
  dirty
  dependencies: [MediaQuery]
  state: _CardStackState#e734f
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 8652): user decision: Like

Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4268 pos 12: '!_dirty': is not true.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while rebuilding dirty elements:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4268 pos 12: '!_dirty': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  CardStack file:///C:/Users/Yoni/Projects/tinderCloneUI/lib/main.dart:123:17
When the exception was thrown, this was the stack: 
#2      Element.rebuild (package:flutter/src/widgets/framework.dart:4268:12)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
#4      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
#5      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
...
The element being rebuilt at the time was index 0 of 2: CardStack
  dirty
  dependencies: [MediaQuery]
  state: _CardStackState#e734f

**Comment by yoniker** [comment]
This might be an issue with the repo,closing the issue for now,will open with a minimal example if need be
